const CREATE = 'CREATE'
const UPDATE = 'UPDATE'
const DELETE = 'DELETE'
const FETCH_ALL = 'FETCH_ALL'
const LIKE = 'LIKE'
const AUTH = 'AUTH'
const LOGOUT = 'LOGOUT'
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'

export {CREATE, UPDATE, DELETE, FETCH_ALL, FETCH_BY_SEARCH, LIKE, AUTH, LOGOUT}  