const CREATE = 'CREATE'
const UPDATE = 'UPDATE'
const DELETE = 'DELETE'
const FETCH_ALL = 'FETCH_ALL'
const LIKE = 'LIKE'
const AUTH = 'AUTH'
const LOGOUT = 'LOGOUT'
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'
const START_LOADING = 'START_LOADING'
const END_LOADING = 'END_LOADING'
const FETCH_POST = 'FETCH_POST'
const COMMENT = 'COMMENT'

export {CREATE, UPDATE, DELETE, FETCH_ALL, FETCH_BY_SEARCH, LIKE, AUTH, LOGOUT, START_LOADING, END_LOADING, FETCH_POST, COMMENT}  